services:
  aliaser:
    image: sixtyfold5687/aliaser:latest
    ports:
      - "8090:80"
    volumes:
      - ./app/json:/var/www/html/json
    environment:
      ALIASER_SECRET_KEY: ${ALIASER_SECRET_KEY:-}
    restart: unless-stopped
